// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudentMgt.Models;
using System;

namespace StudentMgt.Migrations
{
    [DbContext(typeof(StudentMgtContext))]
    [Migration("20180915091902_second migration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentMgt.Models.Marks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Chem");

                    b.Property<float>("Maths");

                    b.Property<float>("Physics");

                    b.HasKey("ID");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("StudentMgt.Models.Student_details", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Reg_No");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Student_details");
                });
#pragma warning restore 612, 618
        }
    }
}
